apiVersion: batch/v1
kind: Job
metadata:
  name: spark-batch-job
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: spark
          image: phaniinturi/spark-app:latest
          imagePullPolicy: Always
      restartPolicy: Never















